extensions:
    ewave-attribute-job-instance-csv-attribute-export-edit-permission:
        module:        pimee/common/tab/permission
        parent:        ewave-attribute-job-instance-csv-attribute-export-edit-tabs
        targetZone:    container
        aclResourceId: pimee_importexport_export_profile_edit_permissions
        position:      100
        config:
            title:   pim_common.permissions
            entity:  job_instance
            tabCode: pim-job-instance-permission

    ewave-attribute-job-instance-xlsx-attribute-export-edit-permission:
        module:        pimee/common/tab/permission
        parent:        ewave-attribute-job-instance-xlsx-attribute-export-edit-tabs
        targetZone:    container
        aclResourceId: pimee_importexport_export_profile_edit_permissions
        position:      100
        config:
            title:   pim_common.permissions
            entity:  job_instance
            tabCode: pim-job-instance-permission
