parameters:
    ewave_attribute.array_converter.flat_to_standard.attribute.class: Ewave\Bundle\AttributeBundle\Rewrites\Akeneo\Pim\Structure\Component\ArrayConverter\FlatToStandard\AttributeConverter

services:
    ewave_attribute.array_converter.flat_to_standard.attribute:
        class:                 '%ewave_attribute.array_converter.flat_to_standard.attribute.class%'
        parent:                pim_connector.array_converter.flat_to_standard.attribute
        decorates:             pim_connector.array_converter.flat_to_standard.attribute
        decoration_inner_name: pim_connector.array_converter.flat_to_standard.attribute.base
        arguments:
            - '@ewave_attribute.property.provider.property_config'
