parameters:
    ewave_attribute.subscriber.updater.attribute_properties.class: Ewave\Bundle\AttributeBundle\EventSubscriber\AttributePropertiesUpdaterSubscriber
    ewave_attribute.subscriber.normalizer.attribute.class:         Ewave\Bundle\AttributeBundle\EventSubscriber\AttributeNormalizerSubscriber

services:
    ewave_attribute.subscriber.updater.attribute_properties:
        class: '%ewave_attribute.subscriber.updater.attribute_properties.class%'
        arguments:
            - '@ewave_attribute.property.provider.property_config'
        tags:
            - { name: kernel.event_subscriber }
        lazy:  true

    ewave_attribute.subscriber.normalizer.attribute:
        class: '%ewave_attribute.subscriber.normalizer.attribute.class%'
        arguments:
            - '@ewave_attribute.property.provider.property_config'
        tags:
            - { name: kernel.event_subscriber }
        lazy:  true
