parameters:
    ewave_attribute.job_parameters.default_values_provider.ewave_csv_attribute_export.class:  Ewave\Bundle\AttributeBundle\JobParameters\DefaultValueProvider\CsvAttributeExport
    ewave_attribute.job_parameters.default_values_provider.ewave_xlsx_attribute_export.class: Ewave\Bundle\AttributeBundle\JobParameters\DefaultValueProvider\XlsxAttributeExport

services:
    # Default Parameters for Exports ----------------------------------------------------------------------------------
    ewave_attribute.job_parameters.default_values_provider.ewave_csv_attribute_export:
        class: '%ewave_attribute.job_parameters.default_values_provider.ewave_csv_attribute_export.class%'
        arguments:
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            -
                - '%ewave_attribute.job_name.csv_attribute_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    ewave_attribute.job_parameters.default_values_provider.ewave_xlsx_attribute_export:
        class: '%ewave_attribute.job_parameters.default_values_provider.ewave_xlsx_attribute_export.class%'
        arguments:
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'
            -
                - '%ewave_attribute.job_name.xlsx_attribute_export%'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
