parameters:
    ewave_attribute.job_name.csv_attribute_export:  'ewave_csv_attribute_export'
    ewave_attribute.job_name.xlsx_attribute_export: 'ewave_xlsx_attribute_export'
    ewave_attribute.connector_name.csv:             'Ewave CSV Connector'
    ewave_attribute.connector_name.xlsx:            'Ewave XLSX Connector'

services:
    ewave_attribute.job.csv_attribute_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%ewave_attribute.job_name.csv_attribute_export%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@ewave_attribute.step.csv_attribute.export'
        tags:
            - { name: akeneo_batch.job, connector: '%ewave_attribute.connector_name.csv%', type: '%pim_connector.job.export_type%' }

    ewave_attribute.job.xlsx_attribute_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%ewave_attribute.job_name.xlsx_attribute_export%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@ewave_attribute.step.xlsx_attribute.export'
        tags:
            - { name: akeneo_batch.job, connector: '%ewave_attribute.connector_name.xlsx%', type: '%pim_connector.job.export_type%' }
