services:
    ### Attribute
    pim_catalog.normalizer.standard.attribute:
        class: 'Ewave\Bundle\AttributeBundle\Normalizer\Standard\AttributeNormalizer'
        arguments:
            - '@pim_catalog.normalizer.standard.translation'
            - '@pim_catalog.normalizer.standard.datetime'
            - ['auto_option_sorting', 'is_read_only', 'default_value']
        tags:
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }
