parameters:
    ewave_attribute.doctrine.query_builder.filter.group.class:      Ewave\Bundle\AttributeBundle\Doctrine\ORM\QueryBuilder\Filter\Attribute\GroupFilter
    ewave_attribute.doctrine.query_builder.filter.type.class:       Ewave\Bundle\AttributeBundle\Doctrine\ORM\QueryBuilder\Filter\Attribute\TypeFilter
    ewave_attribute.doctrine.query_builder.filter.updated.class:    Ewave\Bundle\AttributeBundle\Doctrine\ORM\QueryBuilder\Filter\Attribute\UpdatedFilter
    ewave_attribute.doctrine.query_builder.filter.label.class:      Ewave\Bundle\AttributeBundle\Doctrine\ORM\QueryBuilder\Filter\Attribute\LabelFilter
    ewave_attribute.doctrine.query_builder.filter.identifier.class: Ewave\Bundle\AttributeBundle\Doctrine\ORM\QueryBuilder\Filter\Attribute\IdentifierFilter

services:
    ################ Filters
    ewave_attribute.doctrine.query_builder.filter.group:
        class: '%ewave_attribute.doctrine.query_builder.filter.group.class%'
        arguments:
            - '@pim_catalog.repository.attribute_group'
            - ['group']
            - ['IN']
        tags:
            - { name: ewave_attribute.query_builder.attribute.filter, priority: 90 }

    ewave_attribute.doctrine.query_builder.filter.type:
        class: '%ewave_attribute.doctrine.query_builder.filter.type.class%'
        arguments:
            - ['type']
            - ['IN']
        tags:
            - { name: ewave_attribute.query_builder.attribute.filter, priority: 90 }

    ewave_attribute.doctrine.query_builder.filter.label:
        class: '%ewave_attribute.doctrine.query_builder.filter.label.class%'
        arguments:
            - ['label']
            - ['ALL COMPLETE', 'AT LEAST INCOMPLETE', 'ALL INCOMPLETE']
        tags:
            - { name: ewave_attribute.query_builder.attribute.filter, priority: 90 }

    ewave_attribute.doctrine.query_builder.filter.updated:
        class: '%ewave_attribute.doctrine.query_builder.filter.updated.class%'
        arguments:
            - '@akeneo_batch.job_repository'
            - '@akeneo_batch.job.job_instance_repository'
            - ['updated']
            - ['<', '<=', '>', '>=', '=', '!=', 'SINCE LAST N DAYS', 'SINCE LAST JOB']
        tags:
            - { name: ewave_attribute.query_builder.attribute.filter, priority: 90 }

    ewave_attribute.doctrine.query_builder.filter.identifier:
        class:  '%ewave_attribute.doctrine.query_builder.filter.identifier.class%'
        arguments:
            - ['identifier']
            - ['IN', 'NOT IN']
        tags:
            - { name: ewave_attribute.query_builder.attribute.filter, priority: 90 }

    ################ The main versionable query builder
    ewave_attribute.doctrine.query_builder.attribute.query_builder_adapter:
        class: '%ewave_core.doctrine.query_builder.entity_query_builder_adapter.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@ewave_attribute.doctrine.cursor.attribute.repository_cursor_factory'
            - '@ewave_attribute.doctrine.query_builder.attribute.filter.registry'
            - '@ewave_attribute.doctrine.query_builder.attribute.sorter.registry'

    ################ Cursor factory
    ewave_attribute.doctrine.cursor.attribute.repository_cursor_factory:
        class: '%ewave_core.doctrine.cursor.repository_cursor_factory.class%'
        arguments:
            - '%ewave_core.doctrine.cursor.repository_cursor.class%'
            - '@pim_catalog.repository.attribute'
            - '%pim_job_product_batch_size%'

    ################ Filter registry
    ewave_attribute.doctrine.query_builder.attribute.filter.registry:
        class: '%ewave_core.doctrine.query_builder.filter.registry.class%'
        arguments:
            - !tagged ewave_attribute.query_builder.attribute.filter

    ################ Sorter registry
    ewave_attribute.doctrine.query_builder.attribute.sorter.registry:
        class: '%ewave_core.doctrine.query_builder.sorter.registry.class%'
        arguments:
            - !tagged ewave_attribute.query_builder.attribute.sorter
