config:
    paths:
        # JS modules
        pim/media-field: spygarakeneos3storage/js/product/field/media-field

        # Generator
        spygar-akeneos3storage/media-url-generator:  spygarakeneos3storage/js/generator/media-url-generator
        
        # Templates
        spygar-akeneos3storage/template/product/field/media: spygarakeneos3storage/templates/product/field/media.html
