services:
    pim_catalog.updater.attribute:
        class: 'Ewave\Bundle\AttributeBundle\Updater\AttributeUpdater'
        arguments:
            - '@pim_catalog.repository.attribute_group'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.registry.attribute_type'
            - '@pim_structure.updater.translatable'
            - ['auto_option_sorting', 'is_read_only', 'default_value']