parameters:
    ewave_attribute.validator.properties_validator.class: Ewave\Bundle\AttributeBundle\Validator\Constraints\AttributePropertiesValidator

services:
    ewave_attribute.validator.properties_validator:
        class: '%ewave_attribute.validator.properties_validator.class%'
        arguments:
            - '@ewave_attribute.property.provider.property_config'
            - '@validator'
        tags:
            - { name: validator.constraint_validator, alias: ewave_attribute_properties_validator }
