extensions:
    ewave-attribute-job-instance-xlsx-attribute-export-show:
        module: pim/form/common/edit-form

    ewave-attribute-job-instance-xlsx-attribute-export-show-main-image:
        module:     pim/form/common/main-image
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ExportXLSX.svg

    ewave-attribute-job-instance-xlsx-attribute-export-show-user-navigation:
        module:     pim/menu/user-navigation
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout:      pim_menu.user.logout

    ewave-attribute-job-instance-xlsx-attribute-export-show-breadcrumbs:
        module:     pim/job/common/breadcrumb/breadcrumb
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-show
        targetZone: breadcrumbs

    ewave-attribute-job-instance-xlsx-attribute-export-show-launch:
        module:     pim/job/common/edit/launch
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-show
        targetZone: meta
        position:   110
        config:
            label: pim_import_export.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code

    ewave-attribute-job-instance-xlsx-attribute-export-show-label:
        module:     pim/job/common/edit/label
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-show
        targetZone: title
        position:   100

    ewave-attribute-job-instance-xlsx-attribute-export-show-edit:
        module:        pim/job/common/edit-button
        parent:        ewave-attribute-job-instance-xlsx-attribute-export-show
        targetZone:    buttons
        position:      100
        aclResourceId: pim_importexport_export_profile_edit
        config:
            label:       pim_common.edit
            route:       pim_importexport_export_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code

    ewave-attribute-job-instance-xlsx-attribute-export-show-last-executions:
        module:     akeneojob/controller/job-instance
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-show
        position: 100
        targetZone: content