extensions:
    ewave-attribute-job-instance-xlsx-attribute-export-edit:
        module: pim/form/common/edit-form

    ewave-attribute-job-instance-xlsx-attribute-export-edit-main-image:
        module:     pim/form/common/main-image
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ExportXLSX.svg

    ewave-attribute-job-instance-xlsx-attribute-export-edit-user-navigation:
        module:     pim/menu/user-navigation
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout:      pim_menu.user.logout

    ewave-attribute-job-instance-xlsx-attribute-export-edit-breadcrumbs:
        module:     pim/common/breadcrumbs
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    ewave-attribute-job-instance-xlsx-attribute-export-edit-cache-invalidator:
        module:   pim/cache-invalidator
        parent:   ewave-attribute-job-instance-xlsx-attribute-export-edit
        position: 1000

    ewave-attribute-job-instance-xlsx-attribute-export-edit-tabs:
        module:     pim/form/common/form-tabs
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: content
        position:   100

    ewave-attribute-job-instance-xlsx-attribute-export-edit-properties:
        module:        pim/job/common/edit/properties
        parent:        ewave-attribute-job-instance-xlsx-attribute-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone:    container
        position:      110
        config:
            tabTitle: pim_common.properties
            tabCode:  pim-job-instance-properties

    ewave-attribute-job-instance-xlsx-attribute-export-edit-global:
        module:        pim/job/common/edit/properties
        parent:        ewave-attribute-job-instance-xlsx-attribute-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone:    container
        position:      120
        config:
            tabTitle: pim_enrich.export.product.global_settings.title
            tabCode:  pim-job-instance-global

    ewave-attribute-job-instance-xlsx-attribute-export-edit-content:
        module:        pim/job/product/edit/content
        parent:        ewave-attribute-job-instance-xlsx-attribute-export-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone:    container
        position:      130
        config:
            tabTitle: pim_import_export.form.job_instance.tab.content.title
            tabCode:  pim-job-instance-content

    ewave-attribute-job-instance-xlsx-attribute-export-edit-history:
        module:        pim/common/tab/history
        parent:        ewave-attribute-job-instance-xlsx-attribute-export-edit-tabs
        targetZone:    container
        aclResourceId: pim_importexport_export_profile_history
        position:      140
        config:
            class:   Akeneo\Tool\Component\Batch\Model\JobInstance
            title:   pim_common.history
            tabCode: pim-job-instance-history

    ewave-attribute-job-instance-xlsx-attribute-export-edit-properties-code:
        module:     pim/job/common/edit/field/text
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-properties
        position:   100
        targetZone: properties
        config:
            fieldCode: code
            label:     pim_common.code
            readOnly:  true

    ewave-attribute-job-instance-xlsx-attribute-export-edit-properties-label:
        module:     pim/job/common/edit/field/text
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-properties
        position:   110
        targetZone: properties
        config:
            fieldCode: label
            label:     pim_common.label
            readOnly:  false

    ewave-attribute-job-instance-xlsx-attribute-export-edit-properties-file-path:
        module:     pim/job/common/edit/field/text
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-global
        position:   120
        targetZone: properties
        config:
            fieldCode: configuration.filePath
            readOnly:  false
            label:     pim_import_export.form.job_instance.tab.properties.file_path.title
            tooltip:   pim_import_export.form.job_instance.tab.properties.file_path.help

    ewave-attribute-job-instance-xlsx-attribute-export-edit-properties-lines-per-file:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-xlsx-base-export-edit-global
        position: 130
        targetZone: properties
        config:
            fieldCode: configuration.linesPerFile
            readOnly: false
            label: pim_import_export.form.job_instance.tab.properties.lines_per_file.title
            tooltip: pim_import_export.form.job_instance.tab.properties.lines_per_file.help

    ewave-attribute-job-instance-xlsx-attribute-export-edit-properties-with-header:
        module:     pim/job/common/edit/field/switch
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-global
        position:   150
        targetZone: properties
        config:
            fieldCode: configuration.withHeader
            readOnly:  false
            label:     pim_import_export.form.job_instance.tab.properties.with_header.title
            tooltip:   pim_import_export.form.job_instance.tab.properties.with_header.help

    ewave-attribute-job-instance-xlsx-attribute-export-edit-label:
        module:     pim/job/common/edit/label
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: title
        position:   100

    ewave-attribute-job-instance-xlsx-attribute-export-edit-meta:
        module:     pim/job/common/edit/meta
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: meta
        position:   100

    ewave-attribute-job-instance-xlsx-attribute-export-edit-secondary-actions:
        module:     pim/form/common/secondary-actions
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: buttons
        position:   50

    ewave-attribute-job-instance-xlsx-attribute-export-edit-delete:
        module:        pim/job/export/edit/delete
        parent:        ewave-attribute-job-instance-xlsx-attribute-export-edit-secondary-actions
        targetZone:    secondary-actions
        aclResourceId: pim_importexport_export_profile_remove
        position:      100
        config:
            trans:
                title:    confirmation.remove.export_profile
                subTitle: pim_menu.item.export_profile
                content:  pim_common.confirm_deletion
                success:  pim_import_export.entity.job_instance.flash.delete.success
                failed:   error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    ewave-attribute-job-instance-xlsx-attribute-export-edit-save-buttons:
        module:     pim/form/common/save-buttons
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: buttons
        position:   120

    ewave-attribute-job-instance-xlsx-attribute-export-edit-save:
        module:     pim/job-instance-export-edit-form/save
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: buttons
        position:   0
        config:
            redirectPath: pim_importexport_export_profile_show

    ewave-attribute-job-instance-xlsx-attribute-export-edit-state:
        module:     pim/form/common/state
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit
        targetZone: state
        position:   900
        config:
            entity: pim_import_export.entity.job_instance.label

    ewave-attribute-job-instance-xlsx-attribute-export-edit-validation:
        module: pim/job/common/edit/validation
        parent: ewave-attribute-job-instance-xlsx-attribute-export-edit

    ewave-attribute-job-instance-xlsx-attribute-export-edit-content-structure:
        module:     pim/job/product/edit/content/structure
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-content
        targetZone: structure-filters
        position:   100

    ewave-attribute-job-instance-xlsx-attribute-export-edit-content-structure-scope:
        module:     pim/job/product/edit/content/structure/scope
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-content-structure
        targetZone: filters
        position:   90

    ewave-attribute-job-instance-xlsx-attribute-export-edit-content-structure-locales:
        module:     pim/job/product/edit/content/structure/locales
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-content-structure
        targetZone: filters
        position:   100

    ewave-attribute-job-instance-xlsx-attribute-export-edit-content-data:
        module:     ewave-attribute/job/export/entity/edit/content/data
        parent:     ewave-attribute-job-instance-xlsx-attribute-export-edit-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: group
                    view:  ewave-attribute-entity-attribute-group-filter
                -
                    field: type
                    view:  ewave-attribute-entity-attribute-type-filter
                -
                    field: updated
                    view:  ewave-attribute-entity-updated-filter
                -
                    field: label
                    view:  ewave-attribute-entity-attribute-label-filter
                -
                    field: identifier
                    view:  akeneo-attribute-identifier-filter
