extensions:
    ewave-attribute-job-instance-csv-attribute-export-show:
        module: pim/form/common/edit-form

    ewave-attribute-job-instance-csv-attribute-export-show-main-image:
        module:     pim/form/common/main-image
        parent:     ewave-attribute-job-instance-csv-attribute-export-show
        targetZone: main-image
        config:
            path: bundles/pimui/images/illustrations/ExportCSV.svg

    ewave-attribute-job-instance-csv-attribute-export-show-user-navigation:
        module:     pim/menu/user-navigation
        parent:     ewave-attribute-job-instance-csv-attribute-export-show
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout:      pim_menu.user.logout

    ewave-attribute-job-instance-csv-attribute-export-show-breadcrumbs:
        module:     pim/common/breadcrumbs
        parent:     ewave-attribute-job-instance-csv-attribute-export-show
        targetZone: breadcrumbs
        config:
            tab: pim-menu-exports

    ewave-attribute-job-instance-csv-attribute-export-show-launch:
        module:     pim/job/common/edit/launch
        parent:     ewave-attribute-job-instance-csv-attribute-export-show
        targetZone: meta
        position:   110
        config:
            label: pim_import_export.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_export_launch
            identifier:
                path: code
                name: code

    ewave-attribute-job-instance-csv-attribute-export-show-label:
        module:     pim/job/common/edit/label
        parent:     ewave-attribute-job-instance-csv-attribute-export-show
        targetZone: title
        position:   100

    ewave-attribute-job-instance-csv-attribute-export-show-edit:
        module:        pim/common/redirect
        parent:        ewave-attribute-job-instance-csv-attribute-export-show
        targetZone:    buttons
        position:      100
        aclResourceId: pim_importexport_export_profile_edit
        config:
            label:       pim_common.edit
            route:       pim_importexport_export_profile_edit
            buttonClass: AknButton AknButton--action
            identifier:
                path: code
                name: code

    ewave-attribute-job-instance-csv-attribute-export-show-subsection:
        module:     pim/form/common/subsection
        parent:     ewave-attribute-job-instance-csv-attribute-export-show
        targetZone: content
        config:
            title: pim_import_export.form.job_instance.subsection.last_executions

    ewave-attribute-job-instance-csv-attribute-export-show-grid:
        module:     pim/job/common/grid
        parent:     ewave-attribute-job-instance-csv-attribute-export-show-subsection
        position:   1000
        targetZone: content
        config:
            alias: last-export-executions-grid
            metadata:
                jobType: export
